#!/usr/bin/env bash
# GigSynth provisioning — sets up a Raspberry Pi to boot straight into the rig.
# Generated by `gigsynth -provision`. Re-run after editing the unit file.
set -euo pipefail

MODEL="__MODEL__"
BIN="__BIN__"
SERVICE_NAME="gigsynth-kiosk.service"
UNIT_SRC="$(dirname "$0")/${SERVICE_NAME}"

echo "==> Provisioning GigSynth (${MODEL})"

# 1. Install runtime dependencies (Debian / Raspberry Pi OS).
if command -v apt-get >/dev/null 2>&1; then
  sudo apt-get update
  sudo apt-get install -y libfluidsynth3 librtmidi6 libasound2 libgl1 || \
    sudo apt-get install -y libfluidsynth2 librtmidi5 libasound2 libgl1
fi

# 2. Audio DAC / pisound overlay (uncomment the line that matches the build).
#   echo 'dtoverlay=hifiberry-dac'   | sudo tee -a /boot/firmware/config.txt
#   echo 'dtoverlay=pisound'         | sudo tee -a /boot/firmware/config.txt
#   (DSI touchscreens are detected automatically on Pi OS Bookworm.)

# 3. Install the user systemd service so the rig autostarts at login.
mkdir -p "$HOME/.config/systemd/user"
cp "$UNIT_SRC" "$HOME/.config/systemd/user/${SERVICE_NAME}"
systemctl --user daemon-reload
systemctl --user enable "${SERVICE_NAME}"
loginctl enable-linger "$USER" >/dev/null 2>&1 || true

echo "==> Done. Start now with: systemctl --user start ${SERVICE_NAME}"
echo "    Binary: ${BIN}"
